#!/bin/bash
# git-fshow - git commit browser
#
# https://gist.github.com/akatrevorjay/9fc061e8371529c4007689a696d33c62
# https://asciinema.org/a/101366
#

git-fshow() {
    local g=(
        git log
        --graph
        --pretty=format:"%>(10)%h %<(50,trunc)%s %<(12,trunc)%cr %<(16,trunc)%an"
        --color=always
        "$@"
    )

    local fzf=(
        fzf
        --ansi
        --reverse
        --tiebreak=index
        --no-sort
        --bind=ctrl-s:toggle-sort
        --preview 'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1; }; f {}'
    )

    local sha=(
        awk '{print $3 }'
    )
    local commit=$($g | $fzf | $sha)
    git show $commit
}

git-fshow "$@"

