#!/bin/bash

stats() {
    local log=(
        git log
        --no-merges
        --author="$1"
        --pretty=tformat:
        --numstat
    )

    local parse=(
        awk '{inserted+=$1; \
        deleted+=$2; \
        delta+=$1-$2; \
        ratio=deleted/inserted} \
        END {printf "Commit stats: \
        \n- Lines added (total)....  %s \
        \n- Lines deleted (total)..  %s \
        \n- Total lines (delta)....  %s \
        \n- Add./Del. ratio (1:n)..  1 : %s \
        \n", inserted, deleted, delta, ratio }' -
    )
    $log | $parse
}